#!/usr/bin/env bash
source /perf_apps/liyingli/bench_agentx/router-capacity-20260928/config/b2-real.sh
export RUN_ID=campaign-b2-radix
export RUN=$TRACE_RUNTIME/runs/$RUN_ID
export CONTAINER_PREFIX=llying-campaign-b2
export OLD_PREFIX=llying-campaign-b2-real
export OLD_DECODE_CONTAINER=llying-campaign-b2-real-decode-0
export DECODE_CONTAINER=$CONTAINER_PREFIX-decode-0
export DECODE_SIMULATE_ACC_LEN=3.61
export INFERA_SESSION_AFFINITY=prefill
export DIAG_SOURCE_DECODE=$RUN_ID
export PREVIOUS_RUN=$TRACE_RUNTIME/runs/campaign-b2-radix-real
