#!/usr/bin/env bash
source /perf_apps/liyingli/bench_agentx/router-capacity-20260928/config/b6-real.sh
export RUN_ID=campaign-b6-2p8d8
export RUN=$TRACE_RUNTIME/runs/$RUN_ID
export CONTAINER_PREFIX=llying-campaign-b6
export PREVIOUS_RUN=$TRACE_RUNTIME/runs/campaign-b6-2p8d8-real
export OLD_PREFIX=llying-campaign-b6-real
export TOPOLOGY=/perf_apps/liyingli/bench_agentx/router-capacity-20260928/config/b6.json
export DECODE_SIMULATE_ACC_LEN=3.61
