#!/usr/bin/env bash
source /perf_apps/liyingli/bench_agentx/router-capacity-20260928/config/rb-real.sh
export RUN_ID=campaign-rb-rebaseline
export RUN=$TRACE_RUNTIME/runs/$RUN_ID
export CONTAINER_PREFIX=llying-campaign-rb
export PREVIOUS_RUN=$TRACE_RUNTIME/runs/campaign-rb-rebaseline-real
export OLD_PREFIX=llying-campaign-rb-real
export TOPOLOGY=$TRACE_RUNTIME/config/rb.json
export DECODE_SIMULATE_ACC_LEN=3.61
