#!/usr/bin/env python3
"""The KernelForge add-on, generated from the base format and never beside it.

M3.7.6: *"kernel forge well format one line script 作为额外项目, 在基础格式上封装"* —
**layered over** the flashinfer-bench base, not an alternative to it. A consumer
that does not use KernelForge ignores `operators[].forge` entirely and loses
nothing, because the base carries the whole contract.

Everything here is derived from `definitions/<...>.json` plus
`workloads/<...>.jsonl` plus the operator's row in `workset.yaml`. Nothing is
authored. That is the property `check_workset_shape` checks, by comparing the
exported case list against the workload's — and the reason to check it is the
one `analyze-demo` gave for grading `invocation_spec.json` against
`forge_task.yaml`: two files produced from one record, so a disagreement can
only mean one of them was edited on its own.

Run it as a program, which is how the task readme's STEP 6 invokes it:

    python3 "$PKG/assets/lib/forge_export.py" --workset "$OUT/items/codes"
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

__all__ = ["export_operator", "export_all", "main"]

#: forge-loop parses these off the driver's stdout and treats the driver as a
#: **protected file** its optimising agent may not modify. It therefore takes
#: what the driver prints entirely on trust, which is why `check_workset_runs`
#: exists one level up: something has to have run it.
_DRIVER = '''#!/usr/bin/env python3
"""forge-loop driver for {operator_id}. Generated by assets/lib/forge_export.py.

**Protected.** forge-loop's optimising agent may not modify this file, and
neither may a consumer: it is the same measurement the workset's own entrypoints
make, in the stdout shape forge-loop parses. Editing it makes every number
incomparable with the recorded baseline, which is the whole point of shipping it.

It is a thin adapter and deliberately so — it shells out to
`run_correctness.sh` / `run_performance.sh` rather than re-implementing them, so
there is exactly one instrument in this workset and not two that can disagree.
"""
import argparse, json, pathlib, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
OPERATOR = {operator_id!r}
CASE_IDS = {case_ids!r}


def _run(script, case_id, impl):
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "r.json"
        cmd = [str(ROOT / script), "--operator", OPERATOR, "--json", str(out)]
        if case_id:
            cmd += ["--shape", case_id]
        if impl:
            cmd += ["--impl", impl]
        done = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
        payload = json.loads(out.read_text()) if out.is_file() else {{}}
        return done.returncode, payload


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shape", default="", help="CASE_ID=<id>")
    ap.add_argument("--impl")
    ap.add_argument("--bench-mode", action="store_true")
    ap.add_argument("--profile-run", action="store_true")
    ap.add_argument("--warmup", type=int, default=3)
    ap.add_argument("--iters", type=int, default=10)
    a = ap.parse_args()
    case_id = a.shape.split("=", 1)[1] if "=" in a.shape else None

    if a.bench_mode or a.profile_run:
        rc, payload = _run("run_performance.sh", case_id, a.impl)
        for op in payload.get("operators", []):
            for s in op.get("shapes", []):
                print(f"case_ms: {{s['case_id']}}={{s['weighted_mean_ms']:.6f}}")
                print(f"time_ms: {{s['weighted_mean_ms']:.6f}}")
        return rc

    rc, payload = _run("run_correctness.sh", case_id, a.impl)
    worst = None
    for op in payload.get("operators", []):
        for s in op.get("shapes", []):
            print(f"case_snr: {{s['case_id']}}={{s['snr_db']}}")
            print(f"case_allclose: {{s['case_id']}}={{s['allclose']}}")
            if s["snr_db"] is not None:
                worst = s["snr_db"] if worst is None else min(worst, s["snr_db"])
    print(f"SNR: {{worst if worst is not None else float('nan')}} dB")
    print(f"allclose: {{payload.get('passed', False)}}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
'''

_ONE_LINE = '''#!/bin/sh
# The one-line KernelForge invocation for {operator_id} (M3.7.6).
# Generated by assets/lib/forge_export.py -- edit the base format, not this.
#
# `--dry-run` prints the command without running it, which is the flag that
# makes it reviewable before it books a GPU for hours.
#
# **`kernel-agents forge-loop`, not `forge-loop`.** KernelForge declares exactly
# one console script -- `kernel-agents = "kernel_agents.cli:main"`,
# pyproject.toml:66 -- and `forge-loop` is a click subcommand of it, cli.py:722.
# A bare `forge-loop` does not exist even after a correct install. Found by m4
# while scoping the install, and it was wrong under every option for installing
# it, which is why it was worth fixing before the decision.
#
# **`--workspace` is required and this wrapper cannot supply it.** cli.py:725,
# `required=True`. It names the git checkout KernelForge edits in place, which
# is a site fact like the measurement card -- so it is refused rather than
# defaulted, and for the same reason: a wrong checkout does not fail, it edits
# the wrong tree.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
SPEC="$HERE"/invocation_spec.json
DRIVER="$HERE"/scripts/forge_driver.py
DRY=""
if [ "${{1:-}}" = "--dry-run" ]; then DRY=1; shift; fi
set -- --invocation-spec-file "$SPEC" --driver "$DRIVER" --fellow {fellow} "$@"

# `--workspace=<dir>` and `--workspace <dir>` both have to count, so this
# matches the flag name rather than a spaced token.
HAS_WS=""
for a in "$@"; do case "$a" in --workspace|--workspace=*) HAS_WS=1 ;; esac; done

if [ -n "$DRY" ]; then
  # **Prints even without `--workspace`, and says so in the command it prints.**
  # Dry-run's job is to make the invocation reviewable; refusing here would
  # break that and STEP 6's acceptance with it. The placeholder is deliberately
  # not a valid path, so the printed line cannot be pasted blind.
  printf 'kernel-agents forge-loop'
  for a in "$@"; do printf ' %s' "$a"; done
  [ -n "$HAS_WS" ] || printf ' --workspace <REQUIRED: the git checkout to edit>'
  printf '\\n'
  exit 0
fi

if [ -z "$HAS_WS" ]; then
  echo "run_forge.sh: --workspace is required by kernel-agents forge-loop" >&2
  echo "  (cli.py:725) and names the git checkout it edits in place. This" >&2
  echo "  wrapper cannot know it: the workset describes an operator, not a" >&2
  echo "  checkout." >&2
  echo "  FIX: $0 --workspace <checkout> [other forge-loop flags]" >&2
  exit 2
fi
exec kernel-agents forge-loop "$@"
'''


def export_operator(root: pathlib.Path, operator: dict) -> dict:
    """Write one operator's add-on and return the `forge` block for `workset.yaml`."""
    operator_id = operator["operator_id"]
    directory = root / "operators" / operator_id
    (directory / "scripts").mkdir(parents=True, exist_ok=True)
    (directory / "tests").mkdir(parents=True, exist_ok=True)

    definition = json.loads((root / operator["definition"]).read_text(encoding="utf-8"))
    lines = [json.loads(line) for line in
             (root / operator["workload"]).read_text(encoding="utf-8").splitlines() if line.strip()]
    case_ids = [s["case_id"] for s in operator["shapes"]]
    fellow = _fellow(operator, definition)

    # `tests/cases.json` — the CASE_ID-keyed view forge-loop's `--shape
    # CASE_ID=<id>` selector needs. Order follows the workload, because
    # `check_workset_shape` compares the two as sequences: a set comparison would
    # accept a re-sorted export, and the selector would then pick a different
    # case than a reader of `workset.yaml` expects.
    (directory / "tests" / "cases.json").write_text(json.dumps({
        "operator_id": operator_id,
        "kernel_id": operator.get("kernel_id"),
        "device_symbol": operator.get("device_symbol"),
        "snr_threshold_db": operator["gates"]["snr_db"],
        "generated_from": ["definition", "workload"],
        "cases": [{
            "case_id": shape["case_id"],
            "selector": {"CASE_ID": shape["case_id"], **{k.upper(): v for k, v in shape["axes"].items()}},
            "uuid": shape["uuid"],
            "axes": {**{n: s["value"] for n, s in definition["axes"].items() if s["type"] == "const"},
                     **shape["axes"]},
            "is_primary": bool(shape.get("is_primary")),
            "synthetic": not shape.get("observed", True),
            "role": shape["role"],
        } for shape, _ in zip(operator["shapes"], lines)],
    }, indent=2) + "\n", encoding="utf-8")

    (directory / "invocation_spec.json").write_text(json.dumps({
        "schema_version": 2,
        "status": operator["status"],
        "missing_fields": operator["missing_fields"],
        "logical_operator": operator_id,
        "kernel_id": operator.get("kernel_id"),
        "device_symbol": operator.get("device_symbol"),
        "description": definition.get("description", ""),
        "environment": {"gpu_target": operator.get("_gpu_arch", ""), "framework": "sglang"},
        "implementation": {
            "source_owner": operator["edit_target"].get("source_owner", ""),
            "image_repo_path": operator["edit_target"].get("repo_root_var", ""),
            "sources": operator["edit_target"].get("editable_sources") or [],
            "editable_sources": operator["edit_target"].get("editable_sources") or [],
            "target_kernel_functions": [f for f in [operator["edit_target"].get("entry_function")] if f],
            "source_resolution_method": operator["edit_target"].get("source_resolution_method"),
            "fellow": fellow,
        },
        "tests": {
            "cases_file": "tests/cases.json",
            "driver_contract": {
                "driver": "scripts/forge_driver.py",
                "protected": True,
                "case_selectors": case_ids,
                "selector_flag": "--shape CASE_ID=<id>",
                "correctness_invocation": "python scripts/forge_driver.py",
                "bench_invocation": "python scripts/forge_driver.py --bench-mode",
                "stdout_keys": ["SNR", "allclose", "case_snr", "case_allclose", "case_ms", "time_ms"],
            },
        },
        "targets": {
            "snr_db": operator["gates"]["snr_db"],
            "correctness_gate": "the worst-case SNR over every case must be at or above the threshold",
            # **Not a number.** The standalone baseline lives in
            # `evidence/performance.json` and is the only figure a speedup may be
            # computed against; Magpie's `Avg time (us)` is an in-service average
            # across mixed batch sizes and contention, and the two can differ
            # severalfold. Naming the file instead of copying a number is what
            # stops the wrong one being used.
            "speedup_baseline": "evidence/performance.json, impl=baseline",
        },
    }, indent=2) + "\n", encoding="utf-8")

    (directory / "forge_task.yaml").write_text(_task_yaml(operator, definition, fellow), encoding="utf-8")
    (directory / "scripts" / "forge_driver.py").write_text(
        _DRIVER.format(operator_id=operator_id, case_ids=case_ids), encoding="utf-8")
    one_line = directory / "run_forge.sh"
    one_line.write_text(_ONE_LINE.format(operator_id=operator_id, fellow=fellow), encoding="utf-8")
    one_line.chmod(0o755)

    return {
        "one_line": f"operators/{operator_id}/run_forge.sh",
        "driver": f"operators/{operator_id}/scripts/forge_driver.py",
        "invocation_spec": f"operators/{operator_id}/invocation_spec.json",
        "task": f"operators/{operator_id}/forge_task.yaml",
        "cases": f"operators/{operator_id}/tests/cases.json",
        "generated_from": ["definition", "workload"],
        "fellow": fellow,
    }


def _fellow(operator: dict, definition: dict) -> str:
    """Which KernelForge fellow the kernel's language selects.

    From the Definition's tags rather than guessed from the operator name: the
    tags were written by `identify` off the taxonomy, and a wrong fellow does
    not error — it optimises with the wrong idioms and reports a plausible
    failure hours later.
    """
    for tag in definition.get("tags") or []:
        if isinstance(tag, str) and tag.endswith("-fellow"):
            return tag
    return "generic-fellow"


def _task_yaml(operator: dict, definition: dict, fellow: str) -> str:
    import yaml

    primary = next((s for s in operator["shapes"] if s.get("is_primary")), operator["shapes"][0])
    return yaml.safe_dump({
        "task_id": operator["operator_id"],
        "gpu_target": operator.get("_gpu_arch", ""),
        "fellow": fellow,
        "generated_from": ["definition", "workload"],
        "shapes": {
            "primary": {"CASE_ID": primary["case_id"], **{k.upper(): v for k, v in primary["axes"].items()}},
            "validation": [
                {"CASE_ID": s["case_id"], **{k.upper(): v for k, v in s["axes"].items()}}
                for s in operator["shapes"] if s["case_id"] != primary["case_id"]
            ],
        },
        "targets": {"snr_db": operator["gates"]["snr_db"],
                    "baseline_source": "evidence/performance.json, impl=baseline"},
        "edit_target": operator["edit_target"],
    }, sort_keys=False)


def export_all(root: pathlib.Path) -> int:
    import yaml

    path = root / "workset.yaml"
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    arch = ((document.get("ground_truth") or {}).get("environment") or {}).get("fixed", {}).get("gpu_arch", "")
    for operator in document["operators"]:
        operator["_gpu_arch"] = arch
        operator["forge"] = export_operator(root, operator)
        del operator["_gpu_arch"]
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    print(f"forge_export: {len(document['operators'])} operator(s) exported")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--workset", required=True, help="the workset root, i.e. <handoff>/items/codes")
    return export_all(pathlib.Path(ap.parse_args(argv).workset))


if __name__ == "__main__":
    sys.exit(main())
