#!/usr/bin/env python3
"""Generate a copy of this package with validators removed, for getting a real
chain to *walk* before any verdict is argued about.

**Why a generated copy and not a `--var`.** A `--var` reaches a body through the
program agent's `env:` block (`shared.yaml`, "the only place this package names
its own variables"), and that block belongs to the *runner* agent. A validator
runs in its own validation zone and gets the GLOBAL environment row — which is
why every validator `entry.sh` in this package has to write both
`AGENT_SYS_TASK_PACKAGE` and `AGENT_SYS_DEMO_PACKAGE` fallbacks. So there is no
declared variable a validator can read, and inventing one would be new
machinery on the critical path.

A second `--package` directory needs none: `--package` is already per-run, so
two chains can run side by side, one strict and one permissive, and neither can
disturb the other. That matters right now because five chains are live against
the shared tree and **the package is re-staged at every task start**
(CONTRACT §8a), so an edit to the shared copy reaches every stage not yet begun.

**Never edit the output by hand.** It is regenerated, and a hand edit would be
silently overwritten — or worse, survive and make the two trees disagree about
something other than validators. Everything here is a `validators:` list
rewrite; no other line is touched, and `--report` prints the diff so that claim
is checkable rather than promised.

Usage:

    # everything off — the first real walk on a node
    python3 assets/lib/make_debug_package.py --out /home/yihou/e2e_flow_noval

    # converge back: keep the ones that pass reliably, argue about the rest
    python3 assets/lib/make_debug_package.py --out /home/yihou/e2e_flow_noval \
        --keep check_environment,check_command_parses

    # what would change, without writing anything
    python3 assets/lib/make_debug_package.py --out /tmp/x --report --dry-run

The output is a package directory; point `--package` at it.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

# Matches `  validators: [a, b, c]` and captures the indent, the key and the
# body. Deliberately narrow: an empty list has nothing to remove, and a
# block-style list (`validators:\n  - a`) is not used anywhere in this package
# — asserted below rather than assumed, because a silent miss here would ship a
# "validators off" package that still runs some.
_INLINE = re.compile(r"^(?P<indent>\s*)validators:\s*\[(?P<body>[^\]]*)\]\s*$")
_BLOCK = re.compile(r"^\s*validators:\s*$")

_SKIP_DIRS = {"__pycache__", ".git", ".pytest_cache"}

#: The always-pass validator injected in place of the removed ones. Its body is
#: `assets/check_nothing.validator/check.py`, which ships in the *source* tree
#: (so it is reviewable and version-controlled) but is named in no hand-written
#: `validators:` list there.
BYPASS = "check_nothing"

#: Appended to `steps/common.yaml` in the generated tree. `inputs:` is copied
#: from `check_environment`'s block rather than hard-coded — that validator is
#: declared over all fifteen kinds, so keeping the two lists tied together
#: means a kind added later cannot be silently left out of the bypass.
_DECL = """
# ---------------------------------------------------------------------------
# GENERATED by assets/lib/make_debug_package.py — do not edit, and do not copy
# this block back into the source tree. It admits every handoff unread; see
# assets/check_nothing.validator/check.py for what a green run does and does
# not establish.
- module: validator
  name: {name}
  version: '1'
  brief: Admits every handoff without reading it; validation is disabled for this run
  dimension: completeness
  # `weak` because the schema says strength "qualifies a PASS, never a
  # failure", and this body's PASS is by construction.
  strength: weak
  inputs:
{inputs}
  tags:
    logic_source: external_static
    cost: seconds
    domain: [llm_e2e, common]
"""


def _bypass_declaration(common: str) -> str:
    """Build the `check_nothing` block, copying `check_environment`'s inputs."""
    lines = common.splitlines()
    try:
        at = next(i for i, l in enumerate(lines) if l.strip() == "name: check_environment")
    except StopIteration:
        raise SystemExit(
            "make_debug_package: steps/common.yaml no longer declares "
            "check_environment, so the bypass cannot copy its kind list. "
            "Re-read the file before trusting this tool."
        )
    try:
        start = next(i for i in range(at, len(lines)) if lines[i].strip() == "inputs:")
    except StopIteration:
        raise SystemExit("make_debug_package: check_environment declares no `inputs:`")
    got: list[str] = []
    for l in lines[start + 1 :]:
        if not l.strip().startswith("- "):
            break
        got.append(l)
    if not got:
        raise SystemExit("make_debug_package: check_environment's `inputs:` is empty")
    return _DECL.format(name=BYPASS, inputs="\n".join(got))


def _rewrite(text: str, keep: set[str], where: str) -> tuple[str, list[str]]:
    out: list[str] = []
    notes: list[str] = []
    for lineno, line in enumerate(text.splitlines(keepends=True), 1):
        if _BLOCK.match(line.rstrip("\n")):
            # Refuse rather than skip. A block-style list would sail past
            # `_INLINE` and leave its validators enabled in a tree whose whole
            # purpose is that they are not.
            raise SystemExit(
                f"{where}:{lineno}: block-style `validators:` is not handled by "
                f"this generator, and quietly leaving it enabled would defeat "
                f"the point. Convert it to inline form or extend this script."
            )
        m = _INLINE.match(line.rstrip("\n"))
        if not m:
            out.append(line)
            continue
        names = [n.strip() for n in m["body"].split(",") if n.strip()]
        if not names:
            out.append(line)
            continue
        kept = [n for n in names if n in keep]
        dropped = [n for n in names if n not in keep]
        if not dropped:
            out.append(line)
            continue
        # **`check_nothing` goes on every rewritten kind, even one that keeps
        # some validators.** Two reasons. The framework refuses a kind with an
        # empty list — *"A kind with no validator cannot be admitted"* — so a
        # kind that keeps nothing needs a placeholder anyway. And a kind that
        # keeps something still needs to *say* it is running degraded: this
        # body prints "validation is DISABLED for this run" to stderr, so no
        # verdict from a generated tree can be mistaken for one from the
        # strict tree.
        new = [BYPASS] + kept
        out.append(f"{m['indent']}validators: [{', '.join(new)}]\n")
        notes.append(
            f"{where}:{lineno}: -{','.join(dropped)}"
            + (f"  (kept {','.join(kept)})" if kept else "")
        )
    return "".join(out), notes


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", required=True, help="destination package directory")
    ap.add_argument(
        "--keep",
        default="",
        help="comma-separated validator names to keep; everything else is removed",
    )
    ap.add_argument("--report", action="store_true", help="print every line changed")
    ap.add_argument("--dry-run", action="store_true", help="do not write anything")
    args = ap.parse_args(argv)

    src = Path(__file__).resolve().parent.parent.parent
    if not (src / "main.yaml").is_file():
        print(f"make_debug_package: {src} does not look like the package", file=sys.stderr)
        return 2
    out = Path(args.out).resolve()
    # The deletion rule is absolute and applies to this script as much as to a
    # shell: a destination whose path does not carry `yihou` or `/tmp` is not
    # one this tool is allowed to replace.
    if "yihou" not in str(out) and not str(out).startswith("/tmp"):
        print(
            f"make_debug_package: refusing {out} — the output is removed and "
            f"rewritten, and this path carries neither 'yihou' nor '/tmp'.",
            file=sys.stderr,
        )
        return 2
    if out == src:
        print("make_debug_package: refusing to overwrite the source package", file=sys.stderr)
        return 2

    keep = {n.strip() for n in args.keep.split(",") if n.strip()}
    known = {p.name[: -len(".validator")] for p in (src / "assets").glob("*.validator")}
    unknown = keep - known
    if unknown:
        # A typo in `--keep` would silently drop the validator it meant to
        # keep, which is the failure this whole exercise is trying to avoid.
        print(
            f"make_debug_package: --keep names no such validator: "
            f"{', '.join(sorted(unknown))}",
            file=sys.stderr,
        )
        return 2

    all_notes: list[str] = []
    yamls = sorted(p for p in src.rglob("*.yaml") if not (set(p.parts) & _SKIP_DIRS))
    for p in yamls:
        rel = p.relative_to(src)
        _, notes = _rewrite(p.read_text(), keep, str(rel))
        all_notes.extend(notes)

    if args.report or args.dry_run:
        for n in all_notes:
            print(n)
    print(
        f"make_debug_package: {len(all_notes)} validator list(s) rewritten across "
        f"{len(yamls)} yaml file(s); keeping {sorted(keep) or 'nothing'}",
        file=sys.stderr,
    )
    if args.dry_run:
        return 0

    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(src, out, ignore=shutil.ignore_patterns(*_SKIP_DIRS))
    for p in sorted(out.rglob("*.yaml")):
        rel = p.relative_to(out)
        new, _ = _rewrite(p.read_text(), keep, str(rel))
        p.write_text(new)

    common = out / "steps" / "common.yaml"
    common.write_text(common.read_text() + _bypass_declaration(common.read_text()))

    print(f"make_debug_package: wrote {out}", file=sys.stderr)
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
