#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
PREFILL_HICACHE=1
SMOKE_ONLY=0
READY_TIMEOUT=3600
AGENTX_DURATION=3600
DURATION=3600
AGENTX_WARMUP_REQUESTS_PER_LANE=10
# Preserve automatic sizing; compare small capacity drift against historical A0.
EXPECTED_PREFILL_TOKENS=0
EXPECTED_DECODE_TOKENS=0
EXPECTED_HOST_TOKENS=0
REFERENCE_PREFILL_TOKENS=3143424
REFERENCE_DECODE_TOKENS=3003264
REFERENCE_HOST_TOKENS=4715200
MAX_AUTOMATIC_CAPACITY_RELATIVE_DRIFT=0.001
RUST_LOG=info,infera_router::routing_experiments=warn
PERFORMANCE_CONFIG_CONFIRMATION_REQUIRED=1
