#!/bin/sh
# STEP 3 -- run KernelForge through the workset's OWN one-liner.
#
# `workset.schema.json` gives every operator a `forge.one_line` at
# `operators/<id>/run_forge.sh`, generated by m3 from the same definition the
# tests use (M3.7.6). **Run that.** Do not assemble a `kernel-agents forge-loop`
# command line here: the workset knows its own target functions, its own driver
# and its own architecture, and a hand-written invocation is where
# `--gpu-target gfx942` got copied onto a gfx950 host in the previous round and
# tuned for a chip nobody was measuring.
#
# What this wrapper adds is the environment. Five of the traps in the readme's
# table fail *silently*, and four of them are an unset variable.
#
# POSIX `/bin/sh`: agent_sys invokes a body as `["/bin/sh", entry]`
# (`agent/backends/program.py:83`), so the shebang is never consulted and
# `set -o pipefail` would be a hard exit 2 under dash.
set -eu

INPUTS=""; WORKDIR=""
while [ $# -gt 0 ]; do
  case "$1" in
    --inputs) INPUTS="$2"; shift 2 ;;
    --workdir) WORKDIR="$2"; shift 2 ;;
    *) echo "usage: 30_run_forge.sh --inputs <inputs.json> --workdir <dir>" >&2; exit 1 ;;
  esac
done
[ -n "$INPUTS" ] && [ -n "$WORKDIR" ] || { echo "both --inputs and --workdir are required" >&2; exit 1; }

: "${KFO_SCRATCH_ROOT:?must be local disk inside a yihou/ directory}"
: "${KFO_MOCK:=0}"
: "${KFO_MAX_HOURS:=3.0}"

PY="${KFO_PYTHON:-python3}"
WORKSET=$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["workset_root"])' "$INPUTS")
OPERATOR=$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["operator_id"])' "$INPUTS")
ONELINE=$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["forge_one_line"] or "")' "$INPUTS")

mkdir -p "$WORKDIR"

# --- the environment, built rather than inherited ---------------------------
#
# `TMPDIR` first, and it is the one that fails with a signal rather than a
# message: pointed at a directory that does not exist, EVERY HIP kernel launch
# segfaults with no output while `torch.cuda.is_available()` still returns
# `True`. Measured 2026-09-02 on gfx950; it cost 25 minutes of bisection down to
# a hand-written HIP program, because nothing in the failure names a filesystem.
TMPDIR="${TMPDIR:-$KFO_SCRATCH_ROOT/tmp}"; export TMPDIR
# `$HOME` on this class of host is NFS with root_squash, so a container's root
# maps to nobody and these two fail SILENTLY.
TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$KFO_SCRATCH_ROOT/triton_cache}"; export TRITON_CACHE_DIR
KNOWLEDGE_LOCAL_ROOT="${KNOWLEDGE_LOCAL_ROOT:-$KFO_SCRATCH_ROOT/knowledge}"; export KNOWLEDGE_LOCAL_ROOT
# A config directory with plugins or MCP servers in it makes `claude --print
# --output-format json` return a message ARRAY, and forge's backend probe does
# `payload.get("result")` on it -> `AttributeError: 'list' object has no
# attribute 'get'`. Clean and empty, for the nested process only; the outer
# session's own is never touched.
CLAUDE_CONFIG_DIR="$KFO_SCRATCH_ROOT/claude_config"; export CLAUDE_CONFIG_DIR
mkdir -p "$TMPDIR" "$TRITON_CACHE_DIR" "$KNOWLEDGE_LOCAL_ROOT" "$CLAUDE_CONFIG_DIR"

# --- mock -------------------------------------------------------------------
if [ "$KFO_MOCK" = "1" ]; then
  echo "KFO_MOCK=1: no campaign will be run" >&2
  SEED=$("$PY" - "$INPUTS" "$WORKSET" <<'EOF'
import json, sys, pathlib
pinned = json.load(open(sys.argv[1]))
target = pinned.get("edit_target") or {}
root = pathlib.Path(sys.argv[2])
print(root / (target.get("source_file") or ""))
EOF
)
  if [ ! -f "$SEED" ]; then
    echo "mock: the workset's edit_target names $SEED, which is not there" >&2
    exit 1
  fi
  {
    echo "# MOCK RUN -- KFO_MOCK=1 was set, no KernelForge campaign was run, and this"
    echo "# file is the SEED kernel copied verbatim. There is no optimization in it."
    echo "# Do not integrate it expecting a speedup."
    cat "$SEED"
  } > "$WORKDIR/optimized_kernel.py"
  cat > "$WORKDIR/forge_result.json" <<EOF
{
  "mock": true,
  "_what_this_file_is": "KernelForge did NOT run. KFO_MOCK=1 was set, so there is no campaign output to copy. This file exists because the packup shape expects the slot, and it is filled with nulls rather than plausible-looking numbers so that it cannot be mistaken for a campaign summary.",
  "ran": false,
  "improved": null,
  "mean_case_speedup": null,
  "snr_db": null,
  "iteration_count": 0,
  "operator": "$OPERATOR"
}
EOF
  echo "ok: mock seed written to $WORKDIR/optimized_kernel.py"
  exit 0
fi

# --- the real campaign ------------------------------------------------------
[ -n "$ONELINE" ] || { echo "the workset declares no forge.one_line for $OPERATOR; nothing to run" >&2; exit 1; }

# The floor is 1.0 and it is ENFORCED (`kernel_agents/cli.py:46` MIN_MAX_HOURS,
# `_validate_max_hours` raises `click.BadParameter` below it) -- there is no
# such thing as a five-minute forge run. Clamp, and say so, rather than passing
# a smaller value and letting the CLI reject it.
CLAMPED=$("$PY" -c 'import sys; print(max(1.0, float(sys.argv[1])))' "$KFO_MAX_HOURS")
if [ "$CLAMPED" != "$KFO_MAX_HOURS" ]; then
  echo "note: KFO_MAX_HOURS=$KFO_MAX_HOURS is below the enforced floor; clamped to $CLAMPED" >&2
fi
# At or below 2.0 forge SILENTLY drops Analysis to static-only and the
# implementer turn cap falls 500 -> 100 (`cli.py:1391`, strictly greater than
# `SHORT_FORGE_MAX_HOURS` at `cli.py:47`). Nothing warns you. Recorded so the
# handoff can say `degraded: true` and the README can say SMOKE.
DEGRADED=$("$PY" -c 'import sys; print("true" if float(sys.argv[1]) <= 2.0 else "false")' "$CLAMPED")
echo "$DEGRADED" > "$WORKDIR/degraded"
[ "$DEGRADED" = "true" ] && echo "note: max_hours $CLAMPED <= 2.0 -- this is a SMOKE TEST, analysis will be static-only" >&2

# Forge commits its keeps, and $AGENT_SYS_INPUT_OPERATOR_WORKSET is a sealed
# artefact. Copy, then run in the copy. Never in the input.
RUN="$WORKDIR/repo"
if [ ! -d "$RUN" ]; then
  mkdir -p "$RUN"
  cp -a "$WORKSET/." "$RUN/"
  ( cd "$RUN" && git init -q && git add -A && git commit -qm seed )
fi

KFO_MAX_HOURS="$CLAMPED"; export KFO_MAX_HOURS
KFO_FORGE_WORKDIR="$WORKDIR"; export KFO_FORGE_WORKDIR
echo "running the workset's own one-liner: $ONELINE" >&2
( cd "$RUN" && sh "./$ONELINE" )

# `kernel-agents list --dir` matters here: `config.experiments_dir` defaults to
# `<project_root>/experiments` while forge-loop writes `<workspace>/
# forge_experiments`, so without it you get `No experiments found` and conclude
# the campaign produced nothing.
for candidate in "$RUN/forge_experiments/forge_result.json" "$WORKDIR/forge_result.json"; do
  [ -f "$candidate" ] && [ "$candidate" != "$WORKDIR/forge_result.json" ] && cp "$candidate" "$WORKDIR/forge_result.json"
done
[ -f "$WORKDIR/forge_result.json" ] || { echo "the campaign wrote no forge_result.json" >&2; exit 1; }

KERNEL=$("$PY" - "$RUN" "$WORKSET" "$INPUTS" <<'EOF'
import json, sys, pathlib
run, workset, inputs = pathlib.Path(sys.argv[1]), sys.argv[2], json.load(open(sys.argv[3]))
target = (inputs.get("edit_target") or {}).get("source_file") or ""
print(run / target)
EOF
)
[ -f "$KERNEL" ] || { echo "the campaign left no kernel at $KERNEL" >&2; exit 1; }
cp "$KERNEL" "$WORKDIR/optimized_kernel.py"

# `improved: false` is a legitimate outcome and is not a failure of this step.
echo "ok: campaign finished; kernel at $WORKDIR/optimized_kernel.py"
