#!/bin/sh
# STEP 3 -- run KernelForge through the workset's OWN one-liner.
#
# `workset.schema.json` gives every operator a `forge.one_line` at
# `operators/<id>/run_forge.sh`, generated by m3 from the same definition the
# tests use (M3.7.6). **Run that.** Do not assemble a `kernel-agents forge-loop`
# command line here: the workset knows its own target functions, its own driver
# and its own architecture, and a hand-written invocation is where
# `--gpu-target gfx942` got copied onto a gfx950 host in the previous round and
# tuned for a chip nobody was measuring.
#
# What this wrapper adds is the environment. Five of the traps in the readme's
# table fail *silently*, and four of them are an unset variable.
#
# POSIX `/bin/sh`: agent_sys invokes a body as `["/bin/sh", entry]`
# (`agent/backends/program.py:83`), so the shebang is never consulted and
# `set -o pipefail` would be a hard exit 2 under dash.
set -eu

INPUTS=""; WORKDIR=""
while [ $# -gt 0 ]; do
  case "$1" in
    --inputs) INPUTS="$2"; shift 2 ;;
    --workdir) WORKDIR="$2"; shift 2 ;;
    *) echo "usage: 30_run_forge.sh --inputs <inputs.json> --workdir <dir>" >&2; exit 1 ;;
  esac
done
[ -n "$INPUTS" ] && [ -n "$WORKDIR" ] || { echo "both --inputs and --workdir are required" >&2; exit 1; }

: "${KFO_SCRATCH_ROOT:?must be local disk inside a yihou/ directory}"
: "${KFO_MOCK:=0}"
: "${KFO_MAX_HOURS:=3.0}"

# shellcheck source=/dev/null
. "$(dirname "$0")/_shlib.sh"
PY=$(kfo_python) || exit 1
WORKSET=$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["workset_root"])' "$INPUTS")
OPERATOR=$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["operator_id"])' "$INPUTS")
ONELINE=$("$PY" -c 'import json,sys; print(json.load(open(sys.argv[1]))["forge_one_line"] or "")' "$INPUTS")

mkdir -p "$WORKDIR"

# --- the environment, built rather than inherited ---------------------------
#
# `TMPDIR` first, and it is the one that fails with a signal rather than a
# message: pointed at a directory that does not exist, EVERY HIP kernel launch
# segfaults with no output while `torch.cuda.is_available()` still returns
# `True`. Measured 2026-09-02 on gfx950; it cost 25 minutes of bisection down to
# a hand-written HIP program, because nothing in the failure names a filesystem.
TMPDIR="${TMPDIR:-$KFO_SCRATCH_ROOT/tmp}"; export TMPDIR
# `$HOME` on this class of host is NFS with root_squash, so a container's root
# maps to nobody and these two fail SILENTLY.
TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$KFO_SCRATCH_ROOT/triton_cache}"; export TRITON_CACHE_DIR
KNOWLEDGE_LOCAL_ROOT="${KNOWLEDGE_LOCAL_ROOT:-$KFO_SCRATCH_ROOT/knowledge}"; export KNOWLEDGE_LOCAL_ROOT
# A config directory with plugins or MCP servers in it makes `claude --print
# --output-format json` return a message ARRAY, and forge's backend probe does
# `payload.get("result")` on it -> `AttributeError: 'list' object has no
# attribute 'get'`. Clean and empty, for the nested process only; the outer
# session's own is never touched.
CLAUDE_CONFIG_DIR="$KFO_SCRATCH_ROOT/claude_config"; export CLAUDE_CONFIG_DIR
mkdir -p "$TMPDIR" "$TRITON_CACHE_DIR" "$KNOWLEDGE_LOCAL_ROOT" "$CLAUDE_CONFIG_DIR"

# --- mock -------------------------------------------------------------------
if [ "$KFO_MOCK" = "1" ]; then
  echo "KFO_MOCK=1: no campaign will be run" >&2
  # **The seed is the Definition's `baseline`, NOT `edit_target.source_file`.**
  #
  # Measured 2026-09-04 on crsuse2-m2m-217: seeding from the engine's stock
  # module made STEP 4 refuse with
  #
  #     the Definition's 'candidate:sampler_vocab_softmax' defines no `run`
  #
  # m3's `--impl` contract is a **self-contained** source file exporting a
  # top-level `run(**inputs)`, exec'd in a fresh namespace (`harness/_common.py:278-290`)
  # — no module, no package, no relative imports. The stock `srt/layers/sampler.py`
  # is an sglang module: it exports `Sampler.forward`, not the workset's
  # `integration.public_symbol` (`sampler_softmax`), so even appending a
  # delegation to it raises `NameError`.
  #
  # The Definition's `baseline` already **is** that file — m3 builds it with
  # `build_workset.task/mock_adapt.py:_read_seed()`, which lets the whole source
  # travel verbatim and appends `def run(*a, **k): return <public_symbol>(*a, **k)`.
  # So the mock seeds from the workset's own recorded baseline, which is also
  # what a mock *should* be: the incumbent, unmodified, with no optimisation in
  # it, giving a ratio of ~1.0 against itself by construction.
  #
  # This is also the shape KernelForge's output must take for m3's harness to
  # accept it. Recorded here because the requirement is not obvious from either
  # side alone, and a campaign is an hour before you find out.
  SEED="$WORKDIR/optimized_kernel.py"
  mkdir -p "$WORKDIR"
  "$PY" - "$INPUTS" "$WORKSET" "$SEED" <<'EOF' || exit 1
import json, pathlib, sys
pinned = json.load(open(sys.argv[1]))
root, out = pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
relative = pinned.get("definition")
if not relative:
    sys.exit("mock: STEP 1 pinned no `definition`; cannot find the baseline to seed from")
path = root / str(relative)
if not path.is_file():
    sys.exit(f"mock: the workset names a definition at {relative} that is not there")
source = (json.loads(path.read_text(encoding="utf-8")) or {}).get("baseline")
if not isinstance(source, str) or not source.strip():
    sys.exit(f"mock: {relative} carries no `baseline` source string to seed from")
if "def run(" not in source:
    # Fail rather than append one: if the workset's own baseline does not meet
    # m3's `--impl` contract, that is a finding about the workset and not
    # something this script should paper over.
    sys.exit(f"mock: {relative}'s `baseline` defines no top-level `run`; it cannot be an --impl")
out.write_text(
    "# MOCK RUN -- KFO_MOCK=1 was set, no KernelForge campaign was run, and this\n"
    "# is the WORKSET'S OWN BASELINE, verbatim. There is no optimization in it,\n"
    "# so any ratio measured against it is ~1.0 by construction.\n"
    "# Do not integrate it expecting a speedup.\n" + source + "\n",
    encoding="utf-8",
)
print(f"mock: seeded from {relative}'s baseline ({len(source)} chars)")
EOF
  cat > "$WORKDIR/forge_result.json" <<EOF
{
  "mock": true,
  "_what_this_file_is": "KernelForge did NOT run. KFO_MOCK=1 was set, so there is no campaign output to copy. This file exists because the packup shape expects the slot, and it is filled with nulls rather than plausible-looking numbers so that it cannot be mistaken for a campaign summary.",
  "ran": false,
  "improved": null,
  "mean_case_speedup": null,
  "snr_db": null,
  "iteration_count": 0,
  "operator": "$OPERATOR"
}
EOF
  echo "ok: mock seed written to $WORKDIR/optimized_kernel.py"
  exit 0
fi

# --- the real campaign ------------------------------------------------------
[ -n "$ONELINE" ] || { echo "the workset declares no forge.one_line for $OPERATOR; nothing to run" >&2; exit 1; }

# The floor is 1.0 and it is ENFORCED (`kernel_agents/cli.py:46` MIN_MAX_HOURS,
# `_validate_max_hours` raises `click.BadParameter` below it) -- there is no
# such thing as a five-minute forge run. Clamp, and say so, rather than passing
# a smaller value and letting the CLI reject it.
CLAMPED=$("$PY" -c 'import sys; print(max(1.0, float(sys.argv[1])))' "$KFO_MAX_HOURS")
if [ "$CLAMPED" != "$KFO_MAX_HOURS" ]; then
  echo "note: KFO_MAX_HOURS=$KFO_MAX_HOURS is below the enforced floor; clamped to $CLAMPED" >&2
fi
# At or below 2.0 forge SILENTLY drops two things. Read from the source
# 2026-09-04, correcting an earlier note here that named a constant this
# checkout does not have:
#
#   `LONG_HORIZON_THRESHOLD_HOURS = 2.0`  (cli.py:55)
#   `_is_long_horizon(h) = h > 2.0`       (cli.py:378) -- strictly greater
#
# and it gates EXACTLY two flags, `critic_enabled` (cli.py:997) and
# `profiling_enabled` (cli.py:1157). The option's own help says the same:
# "Budgets >2 hours enable Analysis profiling and, for single-lane rounds,
# Plan Critic review."
#
# **The implementer turn cap is NOT among them.** `config.max_turns` is set
# once from `FORGE_IMPLEMENTER_TURN_BACKSTOP` (cli.py:1706) with no dependence
# on `max_hours`; the "500 -> 100" recorded here before was wrong.
#
# Nothing warns you either way, which is why this is measured rather than
# trusted. Recorded so the handoff can say `degraded: true` and the README can
# say SMOKE.
DEGRADED=$("$PY" -c 'import sys; print("true" if float(sys.argv[1]) <= 2.0 else "false")' "$CLAMPED")
echo "$DEGRADED" > "$WORKDIR/degraded"
[ "$DEGRADED" = "true" ] && echo "note: max_hours $CLAMPED <= 2.0 -- this is a SMOKE TEST, analysis will be static-only" >&2

# $AGENT_SYS_INPUT_OPERATOR_WORKSET is a sealed artefact, and the driver writes
# beside itself. Copy, then run from the copy. Never in the input.
#
# **No `git init` here.** There was one, on the belief that forge commits in the
# directory it is run from. It does not — it commits in `--workspace`
# (`loop/runner.py:1600`), which is the tree built below. A repo here would be
# one nothing ever writes to.
RUN="$WORKDIR/repo"
if [ ! -d "$RUN" ]; then
  mkdir -p "$RUN"
  cp -a "$WORKSET/." "$RUN/"
fi

# --- the workspace: OUR copy of the engine sources, with OUR baseline --------
#
# Ruled 2026-09-04 after reading KernelForge rather than inferring it. Forge
# stages `git add -u` and commits with `cwd=self.ic.workspace_dir`
# (`loop/runner.py:1600`), i.e. `--workspace` (`cli.py:725`, `required=True`)
# and nothing else. So the tree forge edits is a CALLER DECISION, and there are
# three candidates, not two:
#
#   the container's /sgl-workspace/sglang  -- rejected, four reasons below
#   $RUN, the workset copy                 -- rejected: forge would see none of
#                                             the engine sources it exists to
#                                             optimise, and m5's `overlay_files`
#                                             would have nothing to overlay
#   a copy of SGLANG_ROOT, made here       -- this
#
# **Why not the container's checkout.** (1) Modules 1-4 share one container
# (CONTRACT §5), so forge's commits would mutate the tree m2 measured under.
# (2) m5's two-arm design needs a STOCK arm; with the engine tree already
# committed-into there is no stock arm and the comparison silently measures
# nothing. (3) A commit inside a container dies at teardown, so the deliverable
# would live in the one place guaranteed not to outlive the stage. (4) Measured
# on 047 in `inferaimage/infera:sglang-local`: **the image's tree is DIRTY** --
# `git status --porcelain` is 35 lines, 18 modified tracked files and 17
# untracked, all under `python/`. `git diff HEAD` there would have swept
# eighteen unrelated AMD engine modifications into this stage's patch, and every
# one of them would have applied cleanly. That is the reason that produces a
# WRONG ARTEFACT rather than a failure, and it is why this is a copy.
#
# **The baseline commit is load-bearing, not tidiness.** `git add -u` stages
# only *tracked* files, so a `git init` with nothing committed gives forge
# nothing to stage. It does not then emit an empty patch: `runner.py:1600` is
# `check=True`, so it raises `GitError`. Loud, which is the good direction, but
# still the campaign hours already spent.
#
# **The baseline is the tree as the container RUNS it, dirty state and all** --
# not upstream HEAD. m5 overlays onto a container built from this image, so the
# incumbent is the dirty tree; a baseline of upstream HEAD would make every one
# of those 18 files a spurious hunk.
#
# **`git init` at SGLANG_ROOT's level, not at the repo root three above it.**
# Then `git diff HEAD` emits `srt/layers/sampler.py` natively, which is exactly
# `apply.py:637`'s frame — no `--relative`, no path surgery. Cutting the diff in
# the wrong frame is what produced `No file to patch. Skipping patch.` earlier
# in this package; siting the init removes the mismatch instead of compensating
# for it.
#
# 110 MB and 3158 `.py` files, measured; the 3.5 GB is the whole sglang repo and
# the 271 MB `.git` is not copied, since we make our own.
SRC_ROOT=$("$PY" "$(dirname "$0")/resolve_source.py" --inputs "$INPUTS" --what "the stock source") || exit 1
SRC_REL=$("$PY" "$(dirname "$0")/resolve_source.py" --inputs "$INPUTS" --relative) || exit 1
# The root, not the file: `dirname` as many times as `$SRC_REL` has segments
# would be arithmetic on a path. Strip the tail instead, which is exact.
ENGINE_ROOT=${SRC_ROOT%"/$SRC_REL"}
[ "$ENGINE_ROOT" != "$SRC_ROOT" ] || {
  echo "cannot take the engine root: $SRC_ROOT does not end in $SRC_REL" >&2; exit 1; }
[ -d "$ENGINE_ROOT" ] || {
  echo "the engine sources are not at $ENGINE_ROOT -- this step runs OUTSIDE the" >&2
  echo "  engine container, or the image does not carry the tree m3's edit_target names." >&2
  exit 1; }

WS="$WORKDIR/engine_src"
if [ ! -d "$WS/.git" ]; then
  echo "copying the engine sources to $WS (about 110 MB)" >&2
  mkdir -p "$WS"
  cp -a "$ENGINE_ROOT/." "$WS/"
  # **Identity in the REPO, not on our one commit.** `-c user.name=…` would
  # cover the baseline below and nothing else; forge's own commit at
  # `runner.py:1600` passes no identity, so a container with no git config
  # would fail there -- after the campaign hours, which is the expensive place
  # to find it. Same for signing: forge does not pass `--no-gpg-sign`.
  ( cd "$WS" \
    && git init -q \
    && git config user.name "agent-sys m4" \
    && git config user.email "m4@e2e-flow.invalid" \
    && git config commit.gpgsign false \
    && git add -A \
    && git commit -qm "baseline: the engine tree as this container runs it" )
fi

KFO_MAX_HOURS="$CLAMPED"; export KFO_MAX_HOURS
KFO_FORGE_WORKDIR="$WORKDIR"; export KFO_FORGE_WORKDIR
# **This copy is not on any interpreter's import path, and that is only safe
# because m3's `--impl` contract does not import.** The measurement execs the
# candidate file in a fresh namespace (`harness/_common.py:278-290`); nothing
# does `import sglang` and picks the edit up. If that contract ever changes to
# an import, forge will keep editing this tree, the driver will keep measuring
# the container's unmodified one, and **every ratio will come back ~1.0 with no
# error anywhere** — the failure would look like "the optimiser found nothing".
# Recorded at the line that depends on it rather than in a design note.
echo "running the workset's own one-liner: $ONELINE" >&2
echo "  --workspace $WS (a copy; the container's own checkout is not touched)" >&2
( cd "$RUN" && sh "./$ONELINE" --workspace "$WS" )

# `kernel-agents list --dir` matters here: `config.experiments_dir` defaults to
# `<project_root>/experiments` while forge-loop writes `<workspace>/
# forge_experiments`, so without it you get `No experiments found` and conclude
# the campaign produced nothing.
for candidate in "$RUN/forge_experiments/forge_result.json" "$WORKDIR/forge_result.json"; do
  [ -f "$candidate" ] && [ "$candidate" != "$WORKDIR/forge_result.json" ] && cp "$candidate" "$WORKDIR/forge_result.json"
done
[ -f "$WORKDIR/forge_result.json" ] || { echo "the campaign wrote no forge_result.json" >&2; exit 1; }

# **In the workspace, and NOT where `resolve_source.py` points by default.**
# That resolver answers with the *container's* path, which is where the stock
# file is and where the optimised one now is not: forge edited `$WS`. The two
# agree on the tail and only on the tail, which is why `$SRC_REL` is taken from
# the same resolver rather than recomputed.
#
# An earlier note here said "the engine tree, not `$RUN`", reasoning that forge
# edits what m3's spec names through `image_repo_path: @SGLANG_ROOT@`. Wrong
# twice: `image_repo_path` appears nowhere in KernelForge, and the spec is the
# measurement contract, not an edit target.
KERNEL="$WS/$SRC_REL"
[ -f "$KERNEL" ] || { echo "the campaign left no kernel at $KERNEL" >&2; exit 1; }
cp "$KERNEL" "$WORKDIR/optimized_kernel.py"

# **The diff, in `apply.py`'s frame with nothing done to it.** This is what the
# init at `SGLANG_ROOT`'s level bought: `git diff HEAD` from `$WS` heads its
# hunks `a/srt/layers/sampler.py`, which is exactly `split_placeholder`'s tail.
# Empty is a legitimate outcome — forge reverting every candidate is `improved:
# false`, not a failure — so it is written either way and never gated on size.
( cd "$WS" && git diff HEAD ) > "$WORKDIR/engine.patch"

# `improved: false` is a legitimate outcome and is not a failure of this step.
echo "ok: campaign finished; kernel at $WORKDIR/optimized_kernel.py"
