///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.
//
// SPDX-License-Identifier: MIT
///////////////////////////////////////////////////////////////////////////////
//! Byte-exactness of the Kimi-K3 chat encoder against the real Python reference.
//!
//! Kimi-K3 renders chat in imperative Python (`encoding_k3.build_chat_segments`)
//! and ships no Jinja template, so `crate::encoding_k3` is a hand port with
//! nothing but this test standing between it and a silent divergence — and a
//! prefix one token off from the engine's does not error, it just never hits
//! the cache again.
//!
//! `tests/data/kimi_k3_golden.json` is generated by running the engine's own
//! pipeline (sglang's `serving_chat` preparation, then the model's
//! `build_chat_segments`) over each body, with a cross-check that the segments
//! and `apply_chat_template` agree. Segments are compared here with no weights
//! needed; the token ids need `INFERA_TEST_KIMI_K3_DIR`.

use std::path::Path;

use infera_router::encoding_k3::encode_chat;
use infera_router::tiktoken::KimiTokenizer;
use serde_json::Value;

fn golden() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/data/kimi_k3_golden.json"
    );
    serde_json::from_str(&std::fs::read_to_string(path).expect("read golden fixtures"))
        .expect("parse golden fixtures")
}

#[test]
fn segments_match_the_python_reference() {
    let golden = golden();
    let cases = golden["cases"].as_array().expect("cases");
    assert!(cases.len() >= 22, "fixture looks truncated");

    for case in cases {
        let name = case["name"].as_str().unwrap();
        let got = encode_chat(&case["body"])
            .unwrap_or_else(|| panic!("{name}: encoder refused a body the engine renders"));
        let want = case["segments"].as_array().unwrap();

        assert_eq!(
            got.len(),
            want.len(),
            "{name}: segment count differs -- per-segment BPE means a different \
             split is a different token stream, even for identical text\n\
             got:  {:?}\nwant: {:?}",
            got.iter().map(|s| &s.text).collect::<Vec<_>>(),
            want.iter().map(|s| &s[0]).collect::<Vec<_>>(),
        );
        for (i, (got, want)) in got.iter().zip(want).enumerate() {
            assert_eq!(
                (got.text.as_str(), got.allow_special),
                (want[0].as_str().unwrap(), want[1].as_bool().unwrap()),
                "{name}: segment {i} differs",
            );
        }
    }
}

/// The segments above are only half the contract: they still have to tokenize
/// to the ids the engine put in its kv cache.
#[test]
fn token_ids_match_the_python_reference() {
    let Ok(dir) = std::env::var("INFERA_TEST_KIMI_K3_DIR") else {
        eprintln!("skip: set INFERA_TEST_KIMI_K3_DIR to a Kimi-K3 model dir");
        return;
    };
    let tk = KimiTokenizer::load(Path::new(&dir)).expect("load tiktoken");

    let golden = golden();
    for case in golden["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let segments = encode_chat(&case["body"]).unwrap();
        let got = tk.encode_segments(&segments);
        let want: Vec<u32> = case["ids"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as u32)
            .collect();
        assert_eq!(got.len(), want.len(), "{name}: id count differs");
        let first_diff = got.iter().zip(&want).position(|(a, b)| a != b);
        assert!(
            first_diff.is_none(),
            "{name}: ids diverge at {}\ngot:  {:?}\nwant: {:?}",
            first_diff.unwrap(),
            &got[first_diff.unwrap()..(first_diff.unwrap() + 8).min(got.len())],
            &want[first_diff.unwrap()..(first_diff.unwrap() + 8).min(want.len())],
        );
    }
}
