#!/usr/bin/env bash
# 2P1D, each worker TP8/DP8. Source once for launch AND benchmarking.
# Defaults match the final reference P8D8 run; paths belong to this kit.
KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWEEP_TMP_DIR="${SWEEP_TMP_DIR:-$KIT_DIR/.tmp}"
RESULTS_DIR="${RESULTS_DIR:-$KIT_DIR/results}"
PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"

# Shared paths and service identity.
IMAGE="${IMAGE:-infera-sglang:v0519-yihou-0917-nextnfix-hicache}"
EXPECTED_IMAGE_ID="${EXPECTED_IMAGE_ID-sha256:fd7220a57b7d3b58efd875c41f7a9ef46b93469581102d96cbeb6f5451e91d35}"
SGLANG_BASE_IMAGE="${SGLANG_BASE_IMAGE:-lmsysorg/sglang-rocm:v0.5.19-rocm720-mi35x-20260917}"
MODEL="${MODEL:-/shared_nfs/huggingface_models/amd/GLM-5.2-MXFP4}"
SERVED_MODEL="${SERVED_MODEL:-glm5.2-mxfp4}"
CONTROL_NODE="${CONTROL_NODE:-crsuse2-m2m-137}"
BUILDER_NODE="${BUILDER_NODE:-crsuse2-m2m-136}"
REMOTE_BENCH_DIR="${REMOTE_BENCH_DIR:-$KIT_DIR/scripts/bench-harness}"
SSH_USER="${SSH_USER:-xiaobche}"
SSH_OPTS="${SSH_OPTS:--o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new -l $SSH_USER}"

# InferenceX is fetched at this exact commit when AgentX or GSM8K needs it.
INFERENCEX_REPOSITORY="${INFERENCEX_REPOSITORY:-https://github.com/SemiAnalysisAI/InferenceX.git}"
INFERENCEX_REF="${INFERENCEX_REF:-918524ff94045b3f091115f1051c22a8588edf2b}"
INFERENCEX_DIR="${INFERENCEX_DIR:-$SWEEP_TMP_DIR/cache/InferenceX}"
AITER_JIT_CACHE_ROOT="${AITER_JIT_CACHE_ROOT:-$SWEEP_TMP_DIR/cache/aiter}"

# Hardware and container names.
NODE_GPU_COUNT="${NODE_GPU_COUNT:-8}"
PREFILL_GPU_DEVICES="${PREFILL_GPU_DEVICES:-0,1,2,3,4,5,6,7}"
DECODE_GPU_DEVICES="${DECODE_GPU_DEVICES:-0,1,2,3,4,5,6,7}"
CONTAINER_PREFIX="${CONTAINER_PREFIX:-glm52-pd-yaocheng-2p1d}"
GPU_IDLE_VRAM_PCT="${GPU_IDLE_VRAM_PCT:-2}"
GPU_IDLE_TIMEOUT="${GPU_IDLE_TIMEOUT:-3600}"
CONTAINER_STOP_TIMEOUT="${CONTAINER_STOP_TIMEOUT:-300}"

# Ports. The topology row index is added to each worker port base.
ETCD_PORT="${ETCD_PORT:-22379}"
ETCD_PEER_PORT="${ETCD_PEER_PORT:-22380}"
ROUTER_PORT="${ROUTER_PORT:-28000}"
ENGINE_PORT_BASE="${ENGINE_PORT_BASE:-29001}"
BOOTSTRAP_PORT_BASE="${BOOTSTRAP_PORT_BASE:-28998}"
KV_EVENT_PORT_BASE="${KV_EVENT_PORT_BASE:-25557}"
SNAPSHOT_PORT_BASE="${SNAPSHOT_PORT_BASE:-28801}"
INFERA_NODEPORT_RANGE="${INFERA_NODEPORT_RANGE:-30000-32767}"

# Prefill workers: HiCache is enabled here. Decode HiCache remains disabled
# because the current launcher rejects Decode MTP + HiCache.
PREFILL_TP="${PREFILL_TP:-8}"
PREFILL_EP="${PREFILL_EP:-1}"
PREFILL_DP="${PREFILL_DP:-8}"
PREFILL_DPA="${PREFILL_DPA:-1}"
PREFILL_CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-32768}"
PREFILL_MAX_RUNNING="${PREFILL_MAX_RUNNING:-256}"
PREFILL_GRAPH_MAX_BS="${PREFILL_GRAPH_MAX_BS:-256}"
PREFILL_MEM_FRACTION="${PREFILL_MEM_FRACTION:-0.85}"
PREFILL_HSA_NO_SCRATCH_RECLAIM="${PREFILL_HSA_NO_SCRATCH_RECLAIM:-0}"
PREFILL_HICACHE="${PREFILL_HICACHE:-1}"
PREFILL_HICACHE_RATIO="${PREFILL_HICACHE_RATIO:-1.5}"
PREFILL_HICACHE_WRITE_POLICY="${PREFILL_HICACHE_WRITE_POLICY:-write_through}"
PREFILL_HICACHE_IO_BACKEND="${PREFILL_HICACHE_IO_BACKEND:-kernel}"
PREFILL_HICACHE_MEM_LAYOUT="${PREFILL_HICACHE_MEM_LAYOUT:-page_first}"

# Decode worker.
DECODE_TP="${DECODE_TP:-8}"
DECODE_EP="${DECODE_EP:-1}"
DECODE_DP="${DECODE_DP:-8}"
DECODE_DPA="${DECODE_DPA:-1}"
DECODE_CHUNK_SIZE="${DECODE_CHUNK_SIZE:-32768}"
DECODE_MAX_RUNNING="${DECODE_MAX_RUNNING:-256}"
DECODE_GRAPH_MAX_BS="${DECODE_GRAPH_MAX_BS:-256}"
DECODE_MEM_FRACTION="${DECODE_MEM_FRACTION:-0.85}"
DECODE_HSA_NO_SCRATCH_RECLAIM="${DECODE_HSA_NO_SCRATCH_RECLAIM:-1}"
DECODE_HICACHE="${DECODE_HICACHE:-0}"
DECODE_HICACHE_RATIO="${DECODE_HICACHE_RATIO:-1.5}"
DECODE_HICACHE_WRITE_POLICY="${DECODE_HICACHE_WRITE_POLICY:-write_through}"
DECODE_HICACHE_IO_BACKEND="${DECODE_HICACHE_IO_BACKEND:-kernel}"
DECODE_HICACHE_MEM_LAYOUT="${DECODE_HICACHE_MEM_LAYOUT:-page_first}"
DECODE_MTP="${DECODE_MTP:-1}"
DECODE_SPEC_STEPS="${DECODE_SPEC_STEPS:-5}"
DECODE_SPEC_DRAFT_TOKENS="${DECODE_SPEC_DRAFT_TOKENS:-6}"
DECODE_SPEC_TOPK="${DECODE_SPEC_TOPK:-1}"
DECODE_SIMULATE_ACC_LEN="${DECODE_SIMULATE_ACC_LEN-3.61}"

# Match the reference's final run: tilelang, default sgl-kernel top-k,
# IndexShare disabled, fused indexer and custom all-reduce left enabled.
DSA_PREFILL_BACKEND="${DSA_PREFILL_BACKEND:-tilelang}"
DSA_DECODE_BACKEND="${DSA_DECODE_BACKEND:-tilelang}"
DSA_TOPK_BACKEND="${DSA_TOPK_BACKEND-}"
if [[ ! -v JSON_MODEL_OVERRIDE_ARGS ]]; then
    JSON_MODEL_OVERRIDE_ARGS='{"index_share_for_mtp_iteration":false}'
fi

# KV transfer and router.
if [[ ! -v RDMA_DEVICE ]]; then
    RDMA_DEVICE='{"0":"ionic_0","1":"ionic_1","2":"ionic_2","3":"ionic_3","4":"ionic_4","5":"ionic_5","6":"ionic_6","7":"ionic_7"}'
fi
MC_GID_INDEX="${MC_GID_INDEX:-1}"
MC_TE_FILTERS="${MC_TE_FILTERS:-ionic_0,ionic_1,ionic_2,ionic_3,ionic_4,ionic_5,ionic_6,ionic_7}"
MC_ENABLE_DEST_DEVICE_AFFINITY="${MC_ENABLE_DEST_DEVICE_AFFINITY:-1}"
MC_DISABLE_HIP_TRANSPORT="${MC_DISABLE_HIP_TRANSPORT:-1}"
MOONCAKE_DISABLE_HIP_DMABUF="${MOONCAKE_DISABLE_HIP_DMABUF:-0}"
RDMAV_FORK_SAFE="${RDMAV_FORK_SAFE:-1}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}"
SGLANG_OPT_USE_TOPK_V2="${SGLANG_OPT_USE_TOPK_V2:-false}"
SGLANG_OPT_USE_JIT_KERNEL_GROUPED_TOPK="${SGLANG_OPT_USE_JIT_KERNEL_GROUPED_TOPK:-1}"
KV_P2P_TRANSFER="${KV_P2P_TRANSFER:-mooncake}"
ENABLE_KV_AWARE="${ENABLE_KV_AWARE:-1}"
# Keep Decode on the Prefill-selected rank so same-name rail and target GPU
# affinity agree in symmetric DPA deployments.
PD_DP_RANK_AFFINITY="${PD_DP_RANK_AFFINITY:-1}"
KV_PREFILL_OVERLAP_WEIGHT="${KV_PREFILL_OVERLAP_WEIGHT:-20.0}"
KV_DECODE_OVERLAP_WEIGHT="${KV_DECODE_OVERLAP_WEIGHT:-2.0}"
SGLANG_ENABLE_FAILED_SESSION_PROBE="${SGLANG_ENABLE_FAILED_SESSION_PROBE:-1}"
SGLANG_FAILED_SESSION_PROBE_INTERVAL_S="${SGLANG_FAILED_SESSION_PROBE_INTERVAL_S:-30}"
HOST_RDMA_LIB="${HOST_RDMA_LIB:-/lib/x86_64-linux-gnu/libionic.so}"
HOST_RDMA_MOUNT="${HOST_RDMA_MOUNT:-/host-libionic/libionic.so}"

# Build.
BUILD_CONTEXT="${BUILD_CONTEXT:-}"
BUILD_DOCKERFILE="${BUILD_DOCKERFILE:-}"
BUILD_NETWORK="${BUILD_NETWORK:-host}"
BUILD_NO_CACHE="${BUILD_NO_CACHE:-0}"
BUILD_ARGS="${BUILD_ARGS:-}"

# Startup and benchmark targets.
READY_TIMEOUT="${READY_TIMEOUT:-3600}"
ROUTER_READY_TIMEOUT="${ROUTER_READY_TIMEOUT:-300}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-10}"
PREFLIGHT_TIMEOUT="${PREFLIGHT_TIMEOUT:-1800}"
SGLANG_TIMEOUT_KEEP_ALIVE="${SGLANG_TIMEOUT_KEEP_ALIVE:-900}"
CONC="${CONC:-80}"
AGENTX_DURATION="${AGENTX_DURATION:-3600}"
AGENTX_FAILED_REQUEST_THRESHOLD="${AGENTX_FAILED_REQUEST_THRESHOLD:-0.10}"
AGENTX_WARMUP_REQUESTS_PER_LANE="${AGENTX_WARMUP_REQUESTS_PER_LANE:-10}"
AGENTX_CACHE_DIR="${AGENTX_CACHE_DIR:-$SWEEP_TMP_DIR/cache/agentx}"
EVAL_CONCURRENCY="${EVAL_CONCURRENCY:-64}"
EVAL_LIMIT="${EVAL_LIMIT:-}"
TOTAL_CPU_DRAM_GB="${TOTAL_CPU_DRAM_GB:-}"

# Campaign settings. KEY=VALUE arguments override these defaults.
SWEEP_POINTS="${SWEEP_POINTS:-80 112 144 192 256}"
POINT_TIMEOUT="${POINT_TIMEOUT:-21600}"
RUN_PREFLIGHT="${RUN_PREFLIGHT:-1}"
STOP_AFTER_SWEEP="${STOP_AFTER_SWEEP:-1}"
PREFILL_EXTRA_ARGS="${PREFILL_EXTRA_ARGS:-}"
DECODE_EXTRA_ARGS="${DECODE_EXTRA_ARGS:-}"
PREFILL_EXTRA_ENV="${PREFILL_EXTRA_ENV:-}"
DECODE_EXTRA_ENV="${DECODE_EXTRA_ENV:-}"
AITER_ALLREDUCE_FUSION="${AITER_ALLREDUCE_FUSION:-1}"
