#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
PREFILL_HICACHE=0
SMOKE_ONLY=1
SMOKE_CONCURRENCY=80
SMOKE_REQUESTS=80
SMOKE_MAX_NEW_TOKENS=32
SMOKE_TOTAL_BUDGET_SECONDS=900
READY_TIMEOUT=720
RUST_LOG=info
# The no-HiCache stage does not use historical host/capacity assertions.
EXPECTED_PREFILL_TOKENS=0
EXPECTED_DECODE_TOKENS=0
EXPECTED_HOST_TOKENS=0
