#!/usr/bin/env python3
"""`check_one_binary` — completeness, strong.

**Exactly one** executable in the staged content, it runs, it names every
declared case id, and it tells a case id it knows from one it does not.

The count is the requirement rather than a side condition: *"one unified
executable that selects by test case"* is what was asked for, and thirty-six
binaries in a directory would satisfy every other property tested here.

Writes one boolean per handoff id in `inputs.json`.
"""

import json
import shutil
import stat
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "lib"))

import cpp  # noqa: E402 — the path insert above is what makes these importable
import store  # noqa: E402

#: A case id no manifest could contain, used as the **negative control**. A
#: dispatcher that returned 0 for everything would pass every other check here;
#: this is what makes the positive result mean something.
NONSENSE = "zz/no-such-problem-4b1f"

#: `harness`'s exit code for *unknown or missing case id*. Documented in
#: `assets/harness.task/readme.md` and generated by `build.py`.
UNKNOWN_CASE = 2


def executables(root: Path) -> list[Path]:
    """Every executable regular file under the content directory.

    Symlinks are not followed and are not counted: a link to the one binary is
    not a second binary, and a link out of the content is not this validator's
    to chase.
    """
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file() and not path.is_symlink() and (path.stat().st_mode & stat.S_IXUSR)
    )


def runnable_copy(binary: Path, workdir: Path) -> Path:
    """The binary, somewhere it is certainly executable and certainly writable.

    Whether the executable bit survives `env_mgr`'s staging is not something a
    validator body can assume, and it has no business `chmod`ing its own input.
    """
    target = workdir / binary.name
    shutil.copy2(binary, target)
    target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


def spot_case(manifest: dict, case_id: str) -> dict | None:
    """A worked example for the problem `case_id` names, if the manifest has one."""
    problem_id = case_id.split("/", 1)[-1]
    for entry in manifest.get("problems") or []:
        if isinstance(entry, dict) and str(entry.get("problem_id")) == problem_id:
            for example in entry.get("examples") or []:
                if isinstance(example, dict) and example.get("input"):
                    return example
    return None


def check(content: Path) -> tuple[bool, str]:
    """`(verdict, why)`. The reason is printed, so a failure names itself."""
    manifest_path = content / "items" / "manifest.json"
    if not manifest_path.is_file():
        return False, "items/manifest.json does not exist"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return False, f"items/manifest.json is not valid JSON: {exc}"
    if not isinstance(manifest, dict):
        return False, "items/manifest.json is not an object"

    declared = manifest.get("cases")
    if not isinstance(declared, list) or not declared:
        return False, "the manifest declares no cases"
    declared_set = {str(case) for case in declared}

    found = executables(content)
    if len(found) != 1:
        names = [str(path.relative_to(content)) for path in found]
        return False, f"expected exactly one executable, found {len(found)}: {names}"
    binary = found[0]

    named = manifest.get("binary")
    if named and str(binary.relative_to(content / "items")) != str(named):
        return (
            False,
            f"the manifest names {named!r} as the binary but the one executable is "
            f"{binary.relative_to(content / 'items')}",
        )

    workdir = Path(tempfile.mkdtemp(prefix="check-one-binary-"))
    try:
        runnable = runnable_copy(binary, workdir)

        # `--list` on the first line of stdin, not on argv: `cpp.run` passes no
        # argv at all, and `assets/harness.task/readme.md` records that the
        # binary accepts the selector on either channel for exactly this reason.
        rc, out, err, _ = cpp.run(runnable, "--list\n")
        if rc != 0:
            return False, f"`--list` exited {rc}; stderr: {err.strip()[:200]}"
        listed = {line.strip() for line in out.splitlines() if line.strip()}
        if listed != declared_set:
            missing = sorted(declared_set - listed)
            extra = sorted(listed - declared_set)
            return False, f"`--list` disagrees with the manifest: missing {missing}, extra {extra}"

        # The negative control, and it runs BEFORE the positive one on purpose.
        # A dispatcher that ignored its argument would pass the spot-check
        # below; nothing but this distinguishes it from one that works.
        rc, _, _, _ = cpp.run(runnable, f"{NONSENSE}\n")
        if rc != UNKNOWN_CASE:
            return (
                False,
                f"an unknown case id exited {rc}, not {UNKNOWN_CASE}; the binary is not "
                f"discriminating on the case id",
            )

        case_id = sorted(declared_set)[0]
        example = spot_case(manifest, case_id)
        stdin_text = f"{case_id}\n" + (str(example["input"]) if example else "")
        rc, out, err, seconds = cpp.run(runnable, stdin_text)
        if rc == UNKNOWN_CASE:
            return False, f"the binary does not recognise {case_id!r}, which it lists"
        if rc == cpp.TIMEOUT_RETURNCODE:
            return False, f"{case_id!r} did not finish within the run timeout"
        # Whether the ANSWER is right is `score`'s question, not this one. What
        # is required here is that the case id selected something that ran.
        note = "with a worked example" if example else "with empty input"
        return (
            True,
            f"one executable, {len(declared_set)} case ids, `--list` agrees, unknown id "
            f"rejected, {case_id!r} ran {note} in {seconds:.3f}s (rc {rc})",
        )
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def main() -> int:
    results = {}
    for hid in store.inputs():
        content = store.staged_content(hid) or store.content_dir(hid)
        if content is None:
            results[hid], why = False, "no staged content"
        else:
            results[hid], why = check(content)
        print(f"check_one_binary: {hid}: {results[hid]} — {why}")
    store.write_verdict(results)
    return 0


if __name__ == "__main__":
    sys.exit(main())
