#!/bin/bash
echo "### $(hostname)"
echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "kernel: $(uname -r)"
echo "cpu: $(lscpu | awk -F: '/Model name/{gsub(/^ +/,"",$2);print $2;exit}')  cores=$(nproc)"
echo "ram: $(free -g | awk '/^Mem:/{print $2" GB"}')"
echo "rocm: $(cat /opt/rocm/.info/version 2>/dev/null || echo n/a)"
echo "gpu: $(rocm-smi --showproductname 2>/dev/null | grep -oiE 'MI[0-9]+[A-Z]*' | head -1)  count=$(ls -d /sys/class/kfd/kfd/topology/nodes/*/ 2>/dev/null | wc -l)"
echo "amdgpu driver: $(modinfo amdgpu 2>/dev/null | awk '/^version:/{print $2}')"
echo "ionic driver: $(modinfo ionic_rdma 2>/dev/null | awk '/^version:/{print $2}' || echo n/a)"
echo "libionic host: $(readlink -f /usr/lib/x86_64-linux-gnu/libionic.so.1 2>/dev/null)"
echo -n "active ionic rails: "
for d in /sys/class/infiniband/*; do n=$(basename $d); s=$(cat $d/ports/1/state 2>/dev/null); drv=$(basename $(readlink -f $d/device/driver 2>/dev/null)); [[ "$s" == *ACTIVE* && "$drv" == ionic ]] && echo -n "$n "; done; echo
echo "ip_local_port_range: $(cat /proc/sys/net/ipv4/ip_local_port_range)"
echo "docker: $(docker version --format '{{.Server.Version}}')"
echo "image digest: $(docker image inspect infera/engine-sglang:kvaware-kvd --format '{{.Id}}' 2>/dev/null)"
echo "image created: $(docker image inspect infera/engine-sglang:kvaware-kvd --format '{{.Created}}' 2>/dev/null)"
echo "base image: $(docker image inspect infera/engine-sglang:kvaware-kvd-base --format '{{.Id}}' 2>/dev/null)"
echo "sglang: $(docker run --rm --entrypoint python3 infera/engine-sglang:kvaware-kvd -c 'import sglang;print(sglang.__version__)' 2>/dev/null || echo '(see engine log)')"
